"""Render a Diagram as a self-contained HTML page.

The page holds the SVG image inline, so it opens in any browser, can be
attached to an e-mail or a ticket, and needs no network access. Notes
about what the diagram leaves out follow the image.
"""

import html

from flowblueprint import __version__
from flowblueprint.model import Diagram
from flowblueprint.svg import render_svg_str

PAGE_STYLE_STR = """
body { margin: 0; padding: 24px 16px; background: #f6f7f9;
       color: #1d2330; font: 15px/1.5 system-ui, -apple-system,
       "Segoe UI", Roboto, sans-serif; }
main { max-width: 1200px; margin: 0 auto; }
h1 { font-size: 22px; margin: 0 0 4px; }
p.lead { margin: 0 0 16px; color: #4a5468; }
figure { margin: 0; overflow-x: auto; background: #ffffff;
         border: 1px solid #d9dde5; border-radius: 6px; padding: 12px; }
figure svg { display: block; max-width: none; }
h2 { font-size: 16px; margin: 24px 0 8px; }
ul { margin: 0; padding-left: 20px; }
footer { margin-top: 24px; font-size: 13px; color: #6b7487; }
"""


def render_html_str(diagram: Diagram, notes_list: list[str]) -> str:
    """Render a diagram as an HTML page.

    Args:
        diagram: The diagram.
        notes_list: Lines about what the diagram leaves out.

    Returns:
        The HTML document text.
    """
    title_str = html.escape(diagram.title)
    svg_str = render_svg_str(diagram)
    parts_list = [
        "<!doctype html>", '<html lang="en">', "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, '
        'initial-scale=1">',
        f"<title>{title_str} architecture</title>",
        f'<meta name="description" content="Architecture of {title_str}, '
        'generated by FlowBlueprint from the source code.">',
        f'<meta name="generator" content="FlowBlueprint {__version__}">',
        f"<style>{PAGE_STYLE_STR}</style>", "</head>", "<body>", "<main>",
        f"<h1>{title_str}</h1>",
        '<p class="lead">Architecture generated from the source code, '
        "without running it.</p>",
        f"<figure>{svg_str}</figure>"]
    if notes_list:
        parts_list.append("<h2>Not drawn</h2>")
        parts_list.append("<ul>" + "".join(
            f"<li>{html.escape(note_str)}</li>" for note_str in notes_list)
            + "</ul>")
    parts_list.extend([
        f"<footer>FlowBlueprint {__version__}: "
        '<a href="https://github.com/SAMtheROCKET/flowblueprint">'
        "github.com/SAMtheROCKET/flowblueprint</a></footer>",
        "</main>", "</body>", "</html>"])
    return "\n".join(parts_list) + "\n"
